### PR TITLE
#53 error catching to time interp

### LINKED ISSUE #53: more helpful errors, to help end users
PyNEMO at the moment can return unhelpful error messages that don't help end user. E.g. for the benchmark test if ln_dyn_2d is set to true then PyNEMO will crash with an indexing error of an array.

This is due to their being no SSH data that PyNEMO is expecting. However it is not clear from the stack trace or log file that this is the problem.

### PR DESCRIPTION
**Pull request by rdPatmore**
Adding error handling for the time interpolation.

Closes #53 

Tasks:
- [x] set warning for non-uniform time steps
- [x] add warning if using annual means (details in TO DO of time_interpolation() )
- [x] either add IMMERSE logging tasks or create new issue for these
- [x] Test changes are sensible

### CODE REVIEW

**Comment by rdPatmore** [comment]
This is a draft and is not ready for merge.

**Comment by jpolton** [comment]
> This is a draft and is not ready for merge.

(FYI you can convert it to draft in the menu just below the suggested reviewers)

**Comment by rdPatmore** [comment]
Immerse tasks have been created as a new issue, so that this one can be close. There are plenty of tasks that can be done under this banner, but we need to decide on some well defined options. 

Improvements have been made to interp_time() with some error catching. I also found and removed some redundant, non-functioning interpolation code.

The interpolation could be streamlined and made more flexible. Using xarray interpolation could simplify things. There could be a case for a follow-up issue for this.

**Comment by rdPatmore** [comment]
The second warning was not done. The task was based on a TODO in the code. The code noted a possible error case if the existing time-step was not a factor of 86400. I don't think that's an error case.

**Comment by rdPatmore** [comment]
A comment above mentions redundant code. Following a chat with James, this code was not redundant. This code is to be reinstated before pull request goes through.

The removed code was there to handle sub-daily source data. This sub-daily routine did not pass a test with dummy data and needs to be examined after reinstatement.

**Comment by jpolton** [comment]
> A comment above mentions redundant code. Following a chat with James, this code was not redundant. This code is to be reinstated before pull request goes through.
> 
> The removed code was there to handle sub-daily source data. This sub-daily routine did not pass a test with dummy data and needs to be examined after reinstatement.

**Comment by jpolton** [comment]
I pressed the wrong button and closed the PR by mistake. Doh

I was going to query whether @rdPatmore  you have the makings of a unit test, if you have constructed dummy data and know what is it supposed to do?

**Comment by jdha** [comment]
@jpolton just waiting for the template unit test from João and we'll open a new PR for the time interp unit test

**Comment by rdPatmore** [comment]
This is ready for review. I have restored the original interpolation only. Additions of interpolation unit testing can become a new issue.

**Comment by jdha** [comment]
sorry @rdPatmore I've had a visitor all week - I will get back to pyBDY things either this afternoon or first thing Monday. Especially this PR as it would be good to get the time interp sorted and a unit test in place. Will be in touch!

**Comment by jpolton** [comment]
> sorry @rdPatmore I've had a visitor all week - I will get back to pyBDY things either this afternoon or first thing Monday. Especially this PR as it would be good to get the time interp sorted and a unit test in place. Will be in touch!

@jdha since you started on this do you want to finish it. Or shall I review it?

**Review by jdha — APPROVED** [review]
Thanks for putting the code back in - will arrange a meeting after the holidays to discuss improvements to the time interpolation.

**Pull request merged**
